[build]
  publish = "src/public"
  functions = "src/netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
    Access-Control-Allow-Headers = "Content-Type"

[[edge_functions]]
  path = "/api/tmdb/*"
  function = "tmdb-proxy"
  directory = "src/netlify/edge-functions"
